name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.6.7
  hive: ^4.0.0-dev.2
  image_picker: ^1.0.7
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  isar_flutter_libs:
  path_provider: ^2.1.0
  supabase_flutter: ^2.3.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  image_path_android: "assets/app_icon.png"
  image_path_ios: "assets/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 16 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
